### ISSUE TITLE
Cannot add employers - Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by connor11528** [benjaminjdoyle/Perm#1]
On the production site I get a console error when trying to add. Have not tried running locally.

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://perm.herokuapp.com/api/v1/users/profile Failed to load resource: the server responded with a status of 500 (Internal Server Error)
3angular.js:12477TypeError: Cannot read property 'unshift' of undefined
    at HomeController.js:38
    at angular.js:14745
    at n.$eval (angular.js:15989)
    at n.$digest (angular.js:15800)
    at n.$apply (angular.js:16097)
    at h (angular.js:10546)
    at K (angular.js:10744)
    at XMLHttpRequest.z.onload (angular.js:10685)
```

**Comment by benjaminjdoyle** [comment]
Connor,

Thanks for the heads up! I'll take a look.

On Wednesday, February 24, 2016, Connor Leech notifications@github.com
wrote:

> On the production site I get a console error when trying to add. Have not
> tried running locally.
> 
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)http://perm.herokuapp.com/api/v1/users/profile Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> 3angular.js:12477TypeError: Cannot read property 'unshift' of undefined
>     at HomeController.js:38
>     at angular.js:14745
>     at n.$eval (angular.js:15989)
>     at n.$digest (angular.js:15800)
>     at n.$apply (angular.js:16097)
>     at h (angular.js:10546)
>     at K (angular.js:10744)
>     at XMLHttpRequest.z.onload (angular.js:10685)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benjaminjdoyle/Perm/issues/1.

## 

Ben Doyle
